### ISSUE TITLE
Add blockchain REST endpoints

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#170]
Blockchain endpoint(s) should be exposed such that an external Observer may be implemented using standard REST operations (as opposed to using a fabric-sdk).

The following endpoints should be defined, according to https://identity.foundation/sidetree/docs/swagger/#/Blockchain:

- [x] /blockchain/time - #205
- [x] /blockchain/time/{hash} - #208 
- [x] /blockchain/version - #209
- [x] /blockchain/transactions - #212 
- [x] /blockchain/transactions since - #217  
- [x] /blockchain/transactions/firstvalid - #218

**Comment by troyronda** [comment]
Notes: 

- endpoints will be based on configuration such that we can configure which channels / collections are exposed via REST APIs.
- should also define roles/config to control which peers actually expose these endpoints.
