### ISSUE TITLE
Discovery REST endpoint

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#262]
Add a REST endpoint that exposes information about REST endpoints available on a channel.(Available means that the endpoint is healthy.)

This issue depends on the following:

- [x] Application-specific data over Gossip https://github.com/trustbloc/fabric-peer-ext/issues/401
- [x] Discovery provider for REST endpoints https://github.com/trustbloc/sidetree-fabric/issues/328
- [x] Update discovery provider with local services https://github.com/trustbloc/sidetree-fabric/issues/329
- [x] Handler for Discovery endpoint https://github.com/trustbloc/sidetree-fabric/issues/330
- [x] Integration test for service discovery https://github.com/trustbloc/sidetree-fabric/issues/331
