### ISSUE TITLE
Race condition between Observer and Monitor

### ISSUE THREAD

**Issue by bstasyszyn** [trustbloc/sidetree-fabric#306]
The Monitor sometimes checks a batch before the Observer has had a chance, and then starts persisting missing operations. Then, when the Observer gets around to processing the batch, it logs errors such as 'rejecting operation'.

The Monitor 'schedule' should be changed such that it checks a batch only after the Observer has already had a chance to process it.

Will be fixed by the following:

- [x] Combine Observer and Monitor #312 
- [x] Leader election for Observer #313

**Comment by bstasyszyn** [comment]
This issue will be fixed by the following:
- [ ] Combine Observer and Monitor #312 
- [ ] Leader election for Observer #313
